// vue3mvp/mvp_app/src/layout/LayoutApp.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'

import { useAuthStore } from '@/stores/authStore.ts'
import type { BreadcrumbItem, MenuItem } from '@/types/types'
import AppMain from './components/LayoutMain.vue'
import AppMenu from './components/LayoutMenu.vue'
import AppTopbar from './components/LayoutTopbar.vue'

const isCollapse = ref(false)
const loading = ref(false)
const logoutLoading = ref(false)

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

const menus: MenuItem[] = [
  { id: 'user', title: '用户管理', path: '/home/user', icon: 'UserFilled' },
]

const asideWidth = computed(() => (isCollapse.value ? '64px' : '220px'))
const currentUser = computed(() => authStore.currentUserInfo)

const breadcrumbs = computed<BreadcrumbItem[]>(() =>
  route.matched
    .filter((matchedRoute) => matchedRoute.meta.title)
    .map((matchedRoute) => ({
      title: matchedRoute.meta.title as string,
      path: matchedRoute.path,
    })),
)

const toggleSidebar = () => {
  isCollapse.value = !isCollapse.value
}

const handleLogout = async () => {
  const confirmed = await ElMessageBox.confirm('确定退出当前账号吗？', '退出登录', {
    type: 'warning',
    confirmButtonText: '退出',
    cancelButtonText: '取消',
  })
    .then(() => true)
    .catch(() => false)

  if (!confirmed) return

  logoutLoading.value = true

  try {
    await authStore.logoutAction()
    ElMessage.success('已退出登录')
  } catch {
    ElMessage.warning('已清理本地登录状态')
  } finally {
    logoutLoading.value = false
    router.replace('/login')
  }
}

onMounted(async () => {
  loading.value = true
  try {
    await authStore.getAuthAction()
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <el-container class="app-layout">
    <el-aside class="app-aside" :width="asideWidth">
      <AppMenu :collapse="isCollapse" :menus="menus" />
    </el-aside>

    <el-container class="app-body">
      <AppTopbar
        :breadcrumbs="breadcrumbs"
        :collapse="isCollapse"
        :loading="loading || logoutLoading"
        :user="currentUser"
        @toggle-collapse="toggleSidebar"
        @logout="handleLogout"
      />

      <AppMain />
    </el-container>
  </el-container>
</template>

<style scoped lang="less">
.app-layout {
  box-sizing: border-box;
  min-height: 100vh;
  color: #1f2937;
  background: #f4f6fa;
}

.app-layout *,
.app-layout *::before,
.app-layout *::after {
  box-sizing: border-box;
}

.app-body {
  min-width: 0;
  flex-direction: column;
}

.app-aside {
  flex-shrink: 0;
  overflow: hidden;
  background: #172033;
  transition: width 0.2s ease;
}
</style>

// react18mvp/mvp_app/src/layout/LayoutApp.tsx
import { useEffect, useMemo, useState } from 'react'
import { Link, Outlet, useLocation, useNavigate } from 'react-router-dom'
import {
  Bell,
  ChevronDown,
  LogOut,
  Menu,
  PanelLeftClose,
  PanelLeftOpen,
  UserRound,
} from 'lucide-react'

import { useAuth } from '@/store/AuthContext'
import type { BreadcrumbItem, MenuItem } from '@/types/types'
import { notify } from '@/utils/notify'

const menus: MenuItem[] = [
  { id: 'user', title: '用户管理', path: '/home/user', icon: 'UserFilled' },
]

const breadcrumbTitleMap: Record<string, string> = {
  '/home': '首页',
  '/home/user': '用户管理',
}

export default function LayoutApp() {
  const [isCollapse, setIsCollapse] = useState(false)
  const [loading, setLoading] = useState(false)
  const [logoutLoading, setLogoutLoading] = useState(false)
  const [dropdownOpen, setDropdownOpen] = useState(false)

  const auth = useAuth()
  const { clearLoginState, loadCurrentAuth, logout } = auth
  const location = useLocation()
  const navigate = useNavigate()

  const asideWidth = isCollapse ? 64 : 220

  const breadcrumbs = useMemo<BreadcrumbItem[]>(() => {
    const paths = ['/home']

    if (location.pathname !== '/home') {
      paths.push(location.pathname)
    }

    return paths
      .filter((path) => breadcrumbTitleMap[path])
      .map((path) => ({
        title: breadcrumbTitleMap[path],
        path,
      }))
  }, [location.pathname])

  useEffect(() => {
    let active = true

    const loadAuth = async () => {
      setLoading(true)

      try {
        await loadCurrentAuth()
      } finally {
        if (active) setLoading(false)
      }
    }

    loadAuth()

    return () => {
      active = false
    }
  }, [loadCurrentAuth])

  const handleLogout = async () => {
    const confirmed = window.confirm('确定退出当前账号吗？')

    if (!confirmed) return

    setLogoutLoading(true)

    try {
      await logout()
      notify('已退出登录', 'success')
    } catch {
      clearLoginState()
      notify('已清理本地登录状态', 'warning')
    } finally {
      setLogoutLoading(false)
      navigate('/login', { replace: true })
    }
  }

  return (
    <div className="app-layout">
      <aside className="app-aside" style={{ width: asideWidth }}>
        <div className={`brand ${isCollapse ? 'brand-collapsed' : ''}`}>
          <Menu size={22} />
          {!isCollapse && <span className="brand-title">React18 MVP</span>}
        </div>

        <nav className={`side-menu ${isCollapse ? 'side-menu-collapsed' : ''}`}>
          {menus.map((menu) => (
            <Link
              className={`menu-item ${location.pathname === menu.path ? 'menu-item-active' : ''}`}
              key={menu.id}
              to={menu.path}
              title={isCollapse ? menu.title : undefined}
            >
              <UserRound size={18} />
              {!isCollapse && <span>{menu.title}</span>}
            </Link>
          ))}
        </nav>
      </aside>

      <div className="app-body">
        <header className="app-header">
          <div className="header-left">
            <button
              className="icon-button collapse-button"
              onClick={() => setIsCollapse((current) => !current)}
              type="button"
              title={isCollapse ? '展开侧栏' : '收起侧栏'}
            >
              {isCollapse ? <PanelLeftOpen size={20} /> : <PanelLeftClose size={20} />}
            </button>

            {loading ? (
              <div className="breadcrumb-loading" />
            ) : (
              <nav className="breadcrumb">
                {breadcrumbs.map((item, index) => (
                  <span className="breadcrumb-item" key={item.title}>
                    {index > 0 && <span className="breadcrumb-separator">/</span>}
                    {item.path ? <Link to={item.path}>{item.title}</Link> : item.title}
                  </span>
                ))}
              </nav>
            )}
          </div>

          <div className="header-right">
            <button className="icon-button" type="button" title="通知">
              <Bell size={18} />
            </button>

            <div className="user-dropdown">
              <button
                className="user-entry"
                disabled={loading || logoutLoading}
                onClick={() => setDropdownOpen((current) => !current)}
                type="button"
              >
                <span className="avatar">{auth.currentUserInfo?.avatarText || '-'}</span>
                <span>{auth.currentUserInfo?.name || 'Loading'}</span>
                <ChevronDown size={16} />
              </button>

              {dropdownOpen && (
                <div className="dropdown-menu">
                  <button type="button" onClick={handleLogout}>
                    <LogOut size={16} />
                    <span>退出登录</span>
                  </button>
                </div>
              )}
            </div>
          </div>
        </header>

        <main className="app-main">
          <section className="content-panel">
            <Outlet />
          </section>
        </main>
      </div>
    </div>
  )
}
