// react18mvp/mvp_app/src/layout/components/AppTopbar.tsx
import { Avatar, Breadcrumb, Dropdown, Layout } from 'antd'
import type { MenuProps } from 'antd'

import type { BreadcrumbItem } from '@/types/layoutTypes'
import type { UserInfo } from '@/types/userTypes'
import './AppTopbar.css'

interface AppTopbarProps {
  breadcrumbs: BreadcrumbItem[]
  user: UserInfo
  onLogout: () => void
}

export default function AppTopbar({ breadcrumbs, user, onLogout }: AppTopbarProps) {
  const dropdownItems: MenuProps['items'] = [
    {
      key: 'logout',
      label: '退出登录',
      onClick: onLogout,
    },
  ]

  return (
    <Layout.Header className="app-header">
      <div className="header-left">
        {/* 面包屑 */}
        <Breadcrumb
          items={breadcrumbs.map((item) => ({
            title: item.title,
            href: item.path,
          }))}
        />
      </div>

      <div className="header-right">
        {/* 下拉菜单 */}
        <Dropdown menu={{ items: dropdownItems }} trigger={['click']}>
          <div className="user-entry" onClick={(event) => event.preventDefault()}>
            <Avatar size={32}>{user?.name?.slice(0, 1).toUpperCase() || '-'}</Avatar>
            <div>{user?.name || 'Loading'}</div>
          </div>
        </Dropdown>
      </div>
    </Layout.Header>
  )
}

// vue3mvp/mvp_app/src/layout/components/AppTopbar.vue
<script setup lang="ts">

import type {BreadcrumbItem} from '@/types/layoutTypes'
import type {UserInfo} from '@/types/userTypes'

defineProps<{
  breadcrumbs: BreadcrumbItem[]
  user: UserInfo
}>()

defineEmits<{
  logout: []
}>()
</script>

<template>
  <el-header class="app-header">

    <div class="header-left">
      <!-- 面包屑 -->
      <el-breadcrumb separator="/">
        <el-breadcrumb-item v-for="item in breadcrumbs" :key="item.title" :to="item.path">
          {{ item.title }}
        </el-breadcrumb-item>
      </el-breadcrumb>
    </div>

    <div class="header-right">
      <!-- 下拉菜单 -->
      <el-dropdown>
        <div class="user-entry">
          <el-avatar :size="32">
            {{ user?.name?.slice(0, 1).toUpperCase() || '-' }}
          </el-avatar>
          <div>{{ user?.name || 'Loading' }}</div>
        </div>
        <template #dropdown>
          <el-dropdown-menu>
            <el-dropdown-item @click="$emit('logout')">退出登录</el-dropdown-item>
          </el-dropdown-menu>
        </template>
      </el-dropdown>
    </div>

  </el-header>
</template>

<style scoped lang="less">
.app-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 60px;
  width: 100%;
  padding: 0 20px;
  background: #ffffff;
  border-bottom: 1px solid #e5e7eb;
}

.header-left,
.header-right,
.user-entry {
  display: flex;
  align-items: center;
}

.header-left {
  gap: 12px;
  min-width: 0;
}

.header-right {
  gap: 12px;
}

.breadcrumb-loading {
  width: 120px;
}

.breadcrumb-loading :deep(.el-skeleton__first-line) {
  height: 18px;
  margin-top: 0;
}

.user-entry {
  gap: 8px;
  color: #374151;
  cursor: pointer;
  outline: none;
}

@media (max-width: 768px) {
  .app-header {
    padding: 0 12px;
  }
}
</style>
