// vue3mvp/mvp_app/src/views/Login.vue
<script setup lang="ts">
import {onBeforeUnmount, reactive, ref} from 'vue'
import {useRoute, useRouter} from 'vue-router'
import {ElMessage, type FormInstance, type FormRules} from 'element-plus'
import {Cellphone, Lock, Message, User} from '@element-plus/icons-vue'

import {login, register, registerCodeByPhone} from '@/api/apiAuth.ts'
import {useAuthStore} from '@/stores/authStore.ts'

interface LoginForm {
  phone: string
  password: string
}

interface RegisterForm {
  name: string
  phone: string
  smsCode: string
  password: string
  confirmPassword: string
}

type LoginOrRegister = 'login' | 'register'

// router 用于登录成功后跳转，route 用于读取 redirect 参数。
const router = useRouter()
const route = useRoute()

// authStore 只管理 token；登录、注册这些接口调用放在登录页对应流程里。
const authStore = useAuthStore()

// Element Plus 表单实例，用于手动触发表单校验。
const loginFormRef = ref<FormInstance>()
const registerFormRef = ref<FormInstance>()

// loading 控制登录/注册主按钮；sendCodeLoading 单独控制验证码按钮。
const loading = ref(false)
const sendCodeLoading = ref(false)

// 短信倒计时，只影响前端按钮状态；真正的验证码有效期以后端 Redis TTL 为准。
const smsCountdown = ref(0)

// 登录页通过 segmented 在登录表单和注册表单之间切换。
const isLoginOrRegister = ref<LoginOrRegister>('login')

// 保存倒计时定时器 ID，组件卸载时清理，避免离开页面后定时器继续运行。
let countdownTimer: number | undefined

// 登录表单响应式数据，和模板中的 el-form :model 绑定。
const loginForm = reactive<LoginForm>({
  phone: '',
  password: '',
})

// 注册表单响应式数据，字段和后端 /auth/register 参数保持一致。
const registerForm = reactive<RegisterForm>({
  name: '',
  phone: '',
  smsCode: '',
  password: '',
  confirmPassword: '',
})

// 登录校验，原先规则注释保留。
// const loginRules = reactive<FormRules<LoginForm>>({
//   phone: [
//     {required: true, message: '请输入手机号', trigger: 'blur'},
//     {pattern: /^1[3-9]\d{9}$/, message: '手机号格式不正确', trigger: 'blur'},
//   ],
//   password: [{required: true, message: '请输入密码', trigger: 'blur'}],
// })

// 注册校验
const registerRules = reactive<FormRules<RegisterForm>>({
  phone: [
    {required: true, message: '请输入手机号', trigger: 'blur'},
    {pattern: /^1[3-9]\d{9}$/, message: '手机号格式不正确', trigger: 'blur'},
  ],
  smsCode: [
    {required: true, message: '请输入验证码', trigger: 'blur'},
    {pattern: /^\d{6}$/, message: '验证码为 6 位数字', trigger: 'blur'},
  ],
  password: [
    {required: true, message: '请输入密码', trigger: 'blur'},
    {min: 6, message: '密码至少 6 位', trigger: 'blur'},
  ],
  confirmPassword: [
    {required: true, message: '请再次输入密码', trigger: 'blur'},
    {min: 6, message: '密码至少 6 位', trigger: 'blur'},
  ],
  name: [
    {required: true, message: '请输入姓名', trigger: 'blur'},
    {max: 50, message: '姓名长度不能超过 50 位', trigger: 'blur'},
  ],
})

// 登录流程：
// 1. 先触发表单校验；
// 2. 校验通过后调用 /auth/login；
// 3. 登录成功后把响应体中的 accessToken 保存到 authStore；
// 4. refreshToken 不进入前端 JS，由后端通过 HttpOnly Cookie 写入浏览器。
const handleLogin = async () => {
  if (!loginFormRef.value) return

  await loginFormRef.value.validate()
  loading.value = true

  try {
    const tokenResult = await login({
      phone: loginForm.phone,
      password: loginForm.password,
    })
    authStore.setAuthToken(tokenResult)

    ElMessage.success('登录成功')
    handleRedirectToHome()
  } finally {
    loading.value = false
  }
}

// 注册：
// 1. 先校验手机号、验证码、密码、确认密码、姓名；
// 2. 前端再校验一次两次密码是否一致；
// 3. 调用 /auth/register；
// 4. 注册成功后不自动登录，而是切回登录表单，让用户显式登录获取 token。
const handleRegister = async () => {
  if (!registerFormRef.value) return

  await registerFormRef.value.validate()
  if (registerForm.password !== registerForm.confirmPassword) {
    ElMessage.error('两次输入的密码不一致')
    return
  }
  loading.value = true

  try {
    await register({
      name: registerForm.name,
      phone: registerForm.phone,
      password: registerForm.password,
      confirmPassword: registerForm.confirmPassword,
      smsCode: registerForm.smsCode,
    })

    loginForm.phone = registerForm.phone
    loginForm.password = ''
    isLoginOrRegister.value = 'login'
    ElMessage.success('注册成功，请登录')
  } finally {
    loading.value = false
  }
}

// 验证码
// 1. 只校验手机号字段，不要求用户提前填完整注册表单；
// 2. 调用 /auth/register/code；
// 3. 成功后启动前端倒计时。
const handleSmsCode = async () => {
  if (!registerFormRef.value || smsCountdown.value > 0) return

  await registerFormRef.value.validateField('phone')
  sendCodeLoading.value = true

  try {
    await registerCodeByPhone({
      phone: registerForm.phone,
    })

    ElMessage.success('验证码已发送')
    handleSmsCodeCountdown()
  } finally {
    sendCodeLoading.value = false
  }
}

// 验证码按钮倒计时
const handleSmsCodeCountdown = () => {
  smsCountdown.value = 60
  window.clearInterval(countdownTimer)

  countdownTimer = window.setInterval(() => {
    smsCountdown.value -= 1

    if (smsCountdown.value <= 0) {
      window.clearInterval(countdownTimer)
      countdownTimer = undefined
    }
  }, 1000)
}

// 提交
const handleSubmit = () => {
  if (isLoginOrRegister.value === 'login') {
    handleLogin()
    return
  }

  handleRegister()
}

// 登录成功后的跳转目标：
// 1. 如果路由守卫曾经把用户拦到 /login，会带上 redirect；
// 2. 登录成功后优先回到 redirect；
// 3. 没有 redirect 时默认进入 /home。
const handleRedirectToHome = () => {
  const redirect = Array.isArray(route.query.redirect)
      ? route.query.redirect[0]
      : route.query.redirect

  router.replace((redirect as string) || '/home')
}

// 离开登录页时清理倒计时定时器，避免内存泄漏或重复倒计时。
onBeforeUnmount(() => {
  window.clearInterval(countdownTimer)
})
</script>

<template>
  <div class="login-page">
    <div class="login-panel">
      <div class="login-brand">
        <h1>MVP后台管理系统</h1>
      </div>

      <el-segmented class="auth-mode"
                    v-model="isLoginOrRegister"
                    :options="[
                      { label: '登录', value: 'login' },
                      { label: '注册', value: 'register' },
                    ]"
      />

      <!-- 登录表单 -->
      <!-- 原先登录表单规则注释保留：:rules="loginRules" -->
      <el-form class="login-form"
               v-if="isLoginOrRegister === 'login'"
               ref="loginFormRef"
               :model="loginForm"
               size="large"
               @keyup.enter="handleSubmit"
      >
        <el-form-item prop="phone"
                      :rules="[
                        {required: true, message: '请输入手机号', trigger: 'blur'},
                        {pattern: /^1[3-9]\d{9}$/, message: '手机号格式不正确', trigger: 'blur'},
                      ]"
        >
          <el-input v-model="loginForm.phone" placeholder="请输入手机号" :prefix-icon="Cellphone"/>
        </el-form-item>

        <el-form-item prop="password"
                      :rules="[
                        {required: true, message: '请输入密码', trigger: 'blur'},
                      ]"
        >
          <el-input v-model="loginForm.password" placeholder="请输入密码" :prefix-icon="Lock"
                    type="password" show-password/>
        </el-form-item>

        <el-button class="login-button" type="primary" :loading="loading" @click="handleLogin">
          登录
        </el-button>
      </el-form>

      <!-- 注册表单 -->
      <el-form class="login-form"
               v-else
               ref="registerFormRef"
               :model="registerForm"
               :rules="registerRules"
               size="large"
               @keyup.enter="handleSubmit"
      >
        <el-form-item prop="name">
          <el-input v-model="registerForm.name" placeholder="请输入姓名" :prefix-icon="User"/>
        </el-form-item>

        <el-form-item prop="phone">
          <el-input v-model="registerForm.phone" placeholder="请输入手机号" :prefix-icon="Cellphone"/>
        </el-form-item>

        <el-form-item prop="smsCode">
          <div class="sms-code-row">
            <el-input
                v-model="registerForm.smsCode"
                placeholder="请输入验证码"
                :prefix-icon="Message"
            />
            <el-button
                class="sms-code-button"
                :loading="sendCodeLoading"
                :disabled="smsCountdown > 0"
                @click="handleSmsCode"
            >
              {{ smsCountdown > 0 ? `${smsCountdown}s` : '获取验证码' }}
            </el-button>
          </div>
        </el-form-item>

        <el-form-item prop="password">
          <el-input
              v-model="registerForm.password"
              placeholder="请输入密码"
              :prefix-icon="Lock"
              show-password
              type="password"
          />
        </el-form-item>

        <el-form-item prop="confirmPassword">
          <el-input
              v-model="registerForm.confirmPassword"
              placeholder="请再次输入密码"
              :prefix-icon="Lock"
              show-password
              type="password"
          />
        </el-form-item>

        <el-button class="login-button" type="primary" :loading="loading" @click="handleRegister">
          注册
        </el-button>
      </el-form>
    </div>
  </div>
</template>

<style scoped lang="less">
.login-page {
  /* 登录页内部统一盒模型，配合全局清零样式保证面板宽度稳定。 */
  box-sizing: border-box;
  /* 登录页独立于后台布局，铺满整个视口。 */
  display: grid;
  min-height: 100vh;
  place-items: center;
  padding: 24px;
  background: #eef2f8;
}

.login-page *,
.login-page *::before,
.login-page *::after {
  /* 只在登录页范围内继承 border-box，不修改 style.less。 */
  box-sizing: border-box;
}

.login-panel {
  /* 登录表单容器固定最大宽度，避免桌面端过宽。 */
  width: min(100%, 420px);
  padding: 32px;
  background: #ffffff;
  border: 1px solid #e1e6ef;
  border-radius: 8px;
  box-shadow: 0 18px 45px rgb(15 23 42 / 10%);
}

.login-brand {
  /* 品牌区横向排列 logo 和标题。 */
  display: flex;
  align-items: center;
  gap: 14px;
  margin-bottom: 28px;
}

.brand-mark {
  /* 简单文字 logo，后续可替换为真实图片或图标。 */
  display: grid;
  width: 44px;
  height: 44px;
  color: #ffffff;
  font-size: 22px;
  font-weight: 700;
  place-items: center;
  background: #409eff;
  border-radius: 8px;
}

.login-brand h1 {
  margin: 0;
  color: #111827;
  font-size: 24px;
  line-height: 1.2;
}

.login-brand p {
  margin: 4px 0 0;
  color: #64748b;
  font-size: 14px;
}

.auth-mode {
  width: 100%;
  margin-bottom: 22px;
}

.login-form {
  width: 100%;
}

.sms-code-row {
  display: grid;
  width: 100%;
  grid-template-columns: minmax(0, 1fr) 118px;
  gap: 10px;
}

.sms-code-button {
  width: 118px;
}

.login-button {
  width: 100%;
}

@media (max-width: 480px) {
  .login-page {
    padding: 16px;
  }

  .login-panel {
    padding: 24px;
  }

  .sms-code-row {
    grid-template-columns: minmax(0, 1fr) 104px;
  }

  .sms-code-button {
    width: 104px;
    padding-right: 8px;
    padding-left: 8px;
  }
}
</style>

// react18mvp/mvp_app/src/views/Login.tsx
import {Button, Form, Input, message, Segmented} from 'antd'
import {useEffect, useState} from 'react'
import {useLocation, useNavigate} from 'react-router-dom'

import {registerCodeByPhone} from '@/api/apiAuth'
import {authStore} from '@/stores/authStore'
import type {CurrentAuthParams, LoginParams} from '@/types/authTypes'
import './Login.css'

type LoginOrRegister = 'login' | 'register'

interface RegisterForm {
    name: string
    phone: string
    smsCode: string
    password: string
    confirmPassword: string
}

export default function Login() {
    const [loginForm] = Form.useForm<LoginParams>()
    const [registerForm] = Form.useForm<RegisterForm>()
    const [loading, setLoading] = useState(false)
    const [sendCodeLoading, setSendCodeLoading] = useState(false)
    const [smsCountdown, setSmsCountdown] = useState(0)
    const [isLoginOrRegister, setIsLoginOrRegister] = useState<LoginOrRegister>('login')

    const navigate = useNavigate()
    const location = useLocation()

    // 登录流程：
    // 1. 先触发表单校验；
    // 2. 校验通过后调用 authStore.loginAction；
    // 3. authStore 内部会请求真实 /auth/login，并保存响应体中的 accessToken；
    // 4. refreshToken 不进入前端 JS，由后端通过 HttpOnly Cookie 写入浏览器。
    const handleLogin = async () => {
        const values = await loginForm.validateFields()
        setLoading(true)

        try {
            await authStore.loginAction(values)
            message.success('登录成功')
            handleRedirectToHome()
        } finally {
            setLoading(false)
        }
    }

    // 注册：
    // 1. 先校验手机号、验证码、密码、确认密码、姓名；
    // 2. 前端再校验一次两次密码是否一致；
    // 3. 调用 /auth/register；
    // 4. 注册成功后不自动登录，而是切回登录表单，让用户显式登录获取 token。
    const handleRegister = async () => {
        const values = await registerForm.validateFields()

        if (values.password !== values.confirmPassword) {
            message.error('两次输入的密码不一致')
            return
        }

        setLoading(true)

        try {
            await authStore.registerAction(values as CurrentAuthParams)
            loginForm.setFieldsValue({
                phone: values.phone,
                password: '',
            })
            setIsLoginOrRegister('login')
            message.success('注册成功，请登录')
        } finally {
            setLoading(false)
        }
    }

    // 验证码
    // 1. 只校验手机号字段，不要求用户提前填完整注册表单；
    // 2. 调用 /auth/register/code；
    // 3. 成功后启动前端倒计时。
    const handleSmsCode = async () => {
        if (smsCountdown > 0) return

        await registerForm.validateFields(['phone'])
        setSendCodeLoading(true)

        try {
            const phone = registerForm.getFieldValue('phone')
            await registerCodeByPhone({phone})
            message.success('验证码已发送')
            setSmsCountdown(60)
        } finally {
            setSendCodeLoading(false)
        }
    }

    // 登录成功后的跳转目标：
    // 1. 如果路由守卫曾经把用户拦到 /login，会带上 redirect；
    // 2. 登录成功后优先回到 redirect；
    // 3. 没有 redirect 时默认进入 /home。
    const handleRedirectToHome = () => {
        const searchParams = new URLSearchParams(location.search)
        const redirect = searchParams.get('redirect')

        navigate(redirect || '/home', {replace: true})
    }

    // 离开登录页时清理倒计时定时器，避免内存泄漏或重复倒计时。
    useEffect(() => {
        if (smsCountdown <= 0) return undefined

        const timer = window.setInterval(() => {
            setSmsCountdown((current) => Math.max(current - 1, 0))
        }, 1000)

        return () => {
            window.clearInterval(timer)
        }
    }, [smsCountdown])

    return (
        <div className="login-page">
            <div className="login-panel">
                <div className="login-brand">
                    <h1>MVP后台管理系统</h1>
                </div>

                <Segmented<LoginOrRegister>
                    className="auth-mode"
                    value={isLoginOrRegister}
                    options={[
                        {label: '登录', value: 'login'},
                        {label: '注册', value: 'register'},
                    ]}
                    block
                    onChange={setIsLoginOrRegister}
                />

                {isLoginOrRegister === 'login' ? (
                    /* 登录表单 */
                    /* 原先登录表单规则注释保留：rules={loginRules} */
                    <Form className="login-form" form={loginForm} size="large" onFinish={handleLogin}>
                        <Form.Item
                            name="phone"
                            rules={[
                                {required: true, message: '请输入手机号'},
                                {pattern: /^1[3-9]\d{9}$/, message: '手机号格式不正确'},
                            ]}
                        >
                            <Input placeholder="请输入手机号"/>
                        </Form.Item>

                        <Form.Item name="password" rules={[{required: true, message: '请输入密码'}]}>
                            <Input.Password placeholder="请输入密码"/>
                        </Form.Item>

                        <Button className="login-button" type="primary" loading={loading} htmlType="submit">
                            登录
                        </Button>
                    </Form>
                ) : (
                    /* 注册表单 */
                    <Form className="login-form" form={registerForm} size="large" onFinish={handleRegister}>
                        <Form.Item
                            name="name"
                            rules={[
                                {required: true, message: '请输入姓名'},
                                {max: 50, message: '姓名长度不能超过 50 位'},
                            ]}
                        >
                            <Input placeholder="请输入姓名"/>
                        </Form.Item>

                        <Form.Item
                            name="phone"
                            rules={[
                                {required: true, message: '请输入手机号'},
                                {pattern: /^1[3-9]\d{9}$/, message: '手机号格式不正确'},
                            ]}
                        >
                            <Input placeholder="请输入手机号"/>
                        </Form.Item>

                        <div className="sms-code-row">
                            <Form.Item
                                name="smsCode"
                                rules={[
                                    {required: true, message: '请输入验证码'},
                                    {pattern: /^\d{6}$/, message: '验证码为 6 位数字'},
                                ]}
                            >
                                <Input placeholder="请输入验证码"/>
                            </Form.Item>
                            <Button
                                className="sms-code-button"
                                loading={sendCodeLoading}
                                disabled={smsCountdown > 0}
                                onClick={handleSmsCode}
                            >
                                {smsCountdown > 0 ? `${smsCountdown}s` : '获取验证码'}
                            </Button>
                        </div>

                        <Form.Item
                            name="password"
                            rules={[
                                {required: true, message: '请输入密码'},
                                {min: 6, message: '密码至少 6 位'},
                            ]}
                        >
                            <Input.Password placeholder="请输入密码"/>
                        </Form.Item>

                        <Form.Item
                            name="confirmPassword"
                            rules={[
                                {required: true, message: '请再次输入密码'},
                                {min: 6, message: '密码至少 6 位'},
                            ]}
                        >
                            <Input.Password placeholder="请再次输入密码"/>
                        </Form.Item>

                        <Button className="login-button" type="primary" loading={loading} htmlType="submit">
                            注册
                        </Button>
                    </Form>
                )}
            </div>
        </div>
    )
}
